-- MySQL Script generated by MySQL Workbench
-- Sat May 23 10:20:58 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sigma75_apps
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sigma75_apps
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sigma75_apps` DEFAULT CHARACTER SET latin1 ;
USE `sigma75_apps` ;

-- -----------------------------------------------------
-- Table `sigma75_apps`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigma75_apps`.`users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(50) CHARACTER SET 'latin1' COLLATE 'latin1_spanish_ci' NOT NULL,
  `password` VARCHAR(16) CHARACTER SET 'latin1' COLLATE 'latin1_spanish_ci' NOT NULL,
  `email` VARCHAR(255) CHARACTER SET 'latin1' COLLATE 'latin1_general_ci' NOT NULL,
  `authKey` VARCHAR(200) CHARACTER SET 'latin1' COLLATE 'latin1_spanish_ci' NULL DEFAULT NULL,
  `accessToken` VARCHAR(200) CHARACTER SET 'latin1' COLLATE 'latin1_spanish_ci' NULL DEFAULT NULL,
  `activate` INT(11) NOT NULL DEFAULT '0',
  `rubro` VARCHAR(80) CHARACTER SET 'latin1' COLLATE 'latin1_spanish_ci' NOT NULL DEFAULT 'NINGUNO',
  `idPersona` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_spanish_ci;


-- -----------------------------------------------------
-- Table `sigma75_apps`.`apps`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigma75_apps`.`apps` (
  `idApp` VARCHAR(124) NOT NULL,
  `idUser` INT(11) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `codigoApp` VARCHAR(16) NOT NULL COMMENT 'Codigo de la aplicacion que hace referencia',
  `urlLogo` VARCHAR(255) NULL DEFAULT NULL,
  `color1` VARCHAR(16) NULL,
  `color2` VARCHAR(16) NULL,
  `color3` VARCHAR(16) NULL,
  PRIMARY KEY USING BTREE (`idApp`),
  INDEX `idUser` (`idUser` ASC),
  UNIQUE INDEX `idApp_UNIQUE` (`idApp` ASC),
  CONSTRAINT `locales_ibfk_1`
    FOREIGN KEY (`idUser`)
    REFERENCES `sigma75_apps`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sigma75_apps`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigma75_apps`.`productos` (
  `id` INT(11) NOT NULL,
  `app_idApp` VARCHAR(124) NOT NULL,
  `codigo` VARCHAR(124) NULL DEFAULT NULL,
  `nombre` VARCHAR(255) NOT NULL,
  `descripcion` VARCHAR(512) NULL DEFAULT NULL,
  `urlFoto` VARCHAR(255) NULL DEFAULT NULL,
  `estado` VARCHAR(16) NOT NULL DEFAULT 'ACTIVO',
  `precio` DECIMAL(10,2) NOT NULL DEFAULT '0.00',
  `costo` DECIMAL(10,2) NOT NULL DEFAULT '0.00',
  `precio1` DECIMAL(10,2) NOT NULL DEFAULT '0.00',
  `precio2` DECIMAL(10,2) NOT NULL DEFAULT '0.00',
  `opciones` VARCHAR(512) NULL,
  `unidad` VARCHAR(16) NOT NULL DEFAULT 'UNID',
  PRIMARY KEY USING BTREE (`id`, `app_idApp`),
  INDEX `fk_productos_app1_idx` (`app_idApp` ASC),
  CONSTRAINT `fk_productos_app1`
    FOREIGN KEY (`app_idApp`)
    REFERENCES `sigma75_apps`.`apps` (`idApp`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sigma75_apps`.`contacto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigma75_apps`.`contacto` (
  `id` INT NOT NULL,
  `app_idApp` VARCHAR(124) NOT NULL,
  `nombre` VARCHAR(80) NOT NULL,
  `direccion` VARCHAR(255) NOT NULL,
  `localidad` VARCHAR(80) NOT NULL,
  `cel` VARCHAR(20) NOT NULL,
  `tel` VARCHAR(20) NULL,
  `email` VARCHAR(255) NULL,
  `urlFoto` VARCHAR(255) NULL,
  `empresa` VARCHAR(124) NOT NULL DEFAULT '-',
  `cuit` VARCHAR(16) NULL,
  `tipo` VARCHAR(16) NOT NULL DEFAULT 'CLIENTE',
  PRIMARY KEY (`id`, `app_idApp`),
  INDEX `fk_contacto_app1_idx` (`app_idApp` ASC),
  CONSTRAINT `fk_contacto_app1`
    FOREIGN KEY (`app_idApp`)
    REFERENCES `sigma75_apps`.`apps` (`idApp`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigma75_apps`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigma75_apps`.`pedido` (
  `id` INT(11) NOT NULL,
  `app_idApp` VARCHAR(124) NOT NULL,
  `contacto_id` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `fechaIni` DATETIME NOT NULL,
  `fechaFin` DATETIME NULL,
  `fechaEntrega` DATETIME NULL,
  `delivery` TINYINT NOT NULL DEFAULT 0,
  `pedidocol` VARCHAR(45) NULL,
  `monto` DECIMAL(10,2) NULL,
  `descuento` DECIMAL(5,2) NOT NULL DEFAULT '0.00',
  `impuesto` DECIMAL(5,2) NULL DEFAULT '0.00',
  PRIMARY KEY (`id`, `app_idApp`),
  INDEX `fk_pedido_app1_idx` (`app_idApp` ASC),
  INDEX `fk_pedido_contacto1_idx` (`contacto_id` ASC, `app_idApp` ASC),
  CONSTRAINT `fk_pedido_app1`
    FOREIGN KEY (`app_idApp`)
    REFERENCES `sigma75_apps`.`apps` (`idApp`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_contacto1`
    FOREIGN KEY (`contacto_id` , `app_idApp`)
    REFERENCES `sigma75_apps`.`contacto` (`id` , `app_idApp`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sigma75_apps`.`detallePedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigma75_apps`.`detallePedido` (
  `id` INT NOT NULL,
  `cantidad` DECIMAL(10,2) NOT NULL DEFAULT '1.00',
  `detalle` VARCHAR(255) NULL,
  `monto` DECIMAL(10,2) NULL DEFAULT '0.00',
  `fraccion` DECIMAL(10,2) NULL DEFAULT '1.00' COMMENT '\'Para, fracciones, superficie, etc\'',
  `productos_id` INT(11) NOT NULL,
  `pedido_id` INT(11) NOT NULL,
  `pedido_app_idApp` VARCHAR(124) NOT NULL COMMENT 'Para, fracciones, superficie, etc',
  PRIMARY KEY (`id`, `pedido_id`, `pedido_app_idApp`),
  INDEX `fk_detallePedido_productos1_idx` (`productos_id` ASC, `pedido_app_idApp` ASC),
  INDEX `fk_detallePedido_pedido1_idx` (`pedido_id` ASC, `pedido_app_idApp` ASC),
  CONSTRAINT `fk_detallePedido_productos1`
    FOREIGN KEY (`productos_id` , `pedido_app_idApp`)
    REFERENCES `sigma75_apps`.`productos` (`id` , `app_idApp`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detallePedido_pedido1`
    FOREIGN KEY (`pedido_id` , `pedido_app_idApp`)
    REFERENCES `sigma75_apps`.`pedido` (`id` , `app_idApp`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
